CREATE TABLE IF NOT EXISTS users (
  email VARCHAR(100)  NOT NULL PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  identificacion VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);